/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Taller2;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author mundo joven
 */
public class CalculadoraKeyType extends javax.swing.JFrame {

    /**
     * Creates new form MiniCalculadora
     */
    public CalculadoraKeyType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton2 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        campoNumero1 = new javax.swing.JTextField();
        CampoResultado = new javax.swing.JTextField();
        campoNumero2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        respuesta = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        campo = new javax.swing.JTextField();
        multiplicar = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        dividir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        boton2.setText("2");
        boton2.setFocusable(false);
        boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton2MouseClicked(evt);
            }
        });

        boton1.setText("1");
        boton1.setFocusable(false);
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
        });

        boton3.setText("3");
        boton3.setFocusable(false);
        boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton3MouseClicked(evt);
            }
        });

        campoNumero1.setEditable(false);
        campoNumero1.setFocusable(false);

        CampoResultado.setFocusable(false);
        CampoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoResultadoActionPerformed(evt);
            }
        });

        campoNumero2.setEditable(false);
        campoNumero2.setFocusable(false);
        campoNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero2ActionPerformed(evt);
            }
        });

        jLabel2.setText("MI CALCULADORA");
        jLabel2.setFocusable(false);

        respuesta.setText("CALCULAR");
        respuesta.setFocusable(false);
        respuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                respuestaMouseClicked(evt);
            }
        });
        respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaActionPerformed(evt);
            }
        });

        boton4.setText("4");
        boton4.setFocusable(false);
        boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton4MouseClicked(evt);
            }
        });
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton5.setText("5");
        boton5.setFocusable(false);
        boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton5MouseClicked(evt);
            }
        });

        boton6.setText("6");
        boton6.setFocusable(false);
        boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton6MouseClicked(evt);
            }
        });

        boton7.setText("7");
        boton7.setFocusable(false);
        boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton7MouseClicked(evt);
            }
        });

        boton8.setText("8");
        boton8.setFocusable(false);
        boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton8MouseClicked(evt);
            }
        });

        boton9.setText("9");
        boton9.setFocusable(false);
        boton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton9MouseClicked(evt);
            }
        });
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        boton0.setText("0");
        boton0.setFocusable(false);
        boton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton0MouseClicked(evt);
            }
        });
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        campo.setEditable(false);
        campo.setFocusable(false);
        campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoActionPerformed(evt);
            }
        });

        multiplicar.setText("*");
        multiplicar.setFocusable(false);
        multiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicarMouseClicked(evt);
            }
        });

        sumar.setText("+");
        sumar.setFocusable(false);
        sumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumarMouseClicked(evt);
            }
        });

        restar.setText("-");
        restar.setFocusable(false);
        restar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restarMouseClicked(evt);
            }
        });

        dividir.setText("/");
        dividir.setFocusable(false);
        dividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dividirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(respuesta)
                .addGap(187, 187, 187))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(campoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton1)
                                    .addComponent(boton4)
                                    .addComponent(boton7))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(boton2)
                                            .addGap(30, 30, 30)
                                            .addComponent(boton3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(boton5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(boton6)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boton8)
                                        .addGap(30, 30, 30)
                                        .addComponent(boton9))
                                    .addComponent(boton0)))
                            .addComponent(CampoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restar)
                            .addComponent(multiplicar)
                            .addComponent(dividir)
                            .addComponent(sumar))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton2)
                    .addComponent(boton3)
                    .addComponent(boton1)
                    .addComponent(sumar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton4)
                            .addComponent(boton5)
                            .addComponent(boton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton7)
                            .addComponent(boton8)
                            .addComponent(boton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton0))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(restar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(multiplicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dividir)))
                .addGap(8, 8, 8)
                .addComponent(respuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CampoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero2ActionPerformed

    private void CampoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoResultadoActionPerformed

    private void respuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestaActionPerformed

    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("1");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("1");
        }
    }//GEN-LAST:event_boton1MouseClicked

    private void boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("2");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("2");
        }
    }//GEN-LAST:event_boton2MouseClicked

    private void boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("3");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("3");
        }
    }//GEN-LAST:event_boton3MouseClicked

    private void respuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestaMouseClicked
        if(campoNumero1.getText().equals("") | campoNumero2.getText().equals("")| campo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "llenar todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        if (!CampoResultado.equals("")) {
            CampoResultado.setText("");
        }
        int numero1 = Integer.parseInt(campoNumero1.getText());
        int numero2 = Integer.parseInt(campoNumero2.getText());
        int resultado;
        if (campo.getText().equals("+")) {
            resultado = numero1 + numero2;
            CampoResultado.setText(String.valueOf(resultado));
            campoNumero1.setText("");
            campoNumero2.setText("");
            campo.setText("");
        }
        if (campo.getText().equals("-")) {
            resultado = numero1 - numero2;
            CampoResultado.setText(String.valueOf(resultado));
            campoNumero1.setText("");
            campoNumero2.setText("");
            campo.setText("");
        }
        if (campo.getText().equals("*")) {
            resultado = numero1 * numero2;
            CampoResultado.setText(String.valueOf(resultado));
            campoNumero1.setText("");
            campoNumero2.setText("");
            campo.setText("");
        }
        if (campo.getText().equals("/")) {
    if (campoNumero2.getText().equals("0")) {
        JOptionPane.showMessageDialog(null, "Math error", "ERROR", JOptionPane.ERROR_MESSAGE);
        campoNumero1.setText("");
        campoNumero2.setText("");
        campo.setText("");
    } else {
        resultado = numero1 / numero2;
        CampoResultado.setText(String.valueOf(resultado));
        campoNumero1.setText("");
        campoNumero2.setText("");
        campo.setText("");
    }
        }
    }//GEN-LAST:event_respuestaMouseClicked

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        String numero = String.valueOf(evt.getKeyChar());
        
       

        if (numero.equals("1")) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("1");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("1");
            }
        }

        if (numero.equals("2")) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("2");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("2");
            }
        }

        if (numero.equals("3")) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("3");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("3");
            }
        }
        if (numero.equals("4")) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("4");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("4");
            }
        }
        if (numero.equals("5")) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("5");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("5");
            }
        }

        if (numero.equals("6")) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("6");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("6");
            }
        }

        if (numero.equals("7")) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("7");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("7");
            }
        }

        if (numero.equals("8")) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("8");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("8");
            }
        }

        if (numero.equals("9")) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("9");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("9");
            }
        }

        if (numero.equals("0")) {
            if (campo.getText().equals("")) {
                campo.setText("0");
            } else if (campoNumero2.getText().equals("")) {
                campoNumero2.setText("0");
            }
        }

        if (numero.equals("*")) {
            if (campo.getText().equals("")) {
                campo.setText("*");
            }
        }
        if (numero.equals("+")) {
            if (campo.getText().equals("")) {
                campo.setText("+");
            }
        }
        if (numero.equals("-")) {
            if (campo.getText().equals("")) {
                campo.setText("-");
            }
        }
        if (numero.equals("/")) {
            if (campo.getText().equals("")) {
                campo.setText("/");
            }
        }


    }//GEN-LAST:event_formKeyTyped

    private void boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("4");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("4");
}    }//GEN-LAST:event_boton4MouseClicked

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("5");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("5");
        }
    }//GEN-LAST:event_boton5MouseClicked

    private void boton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton6MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("6");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("6");
        }
    }//GEN-LAST:event_boton6MouseClicked

    private void boton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton7MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("7");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("7");
        }
    }//GEN-LAST:event_boton7MouseClicked

    private void boton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton8MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("8");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("8");
        }
    }//GEN-LAST:event_boton8MouseClicked

    private void boton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton9MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("9");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("9");
        }
    }//GEN-LAST:event_boton9MouseClicked

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton0MouseClicked
        if (campoNumero1.getText().equals("")) {
            campoNumero1.setText("0");
        } else if (campoNumero2.getText().equals("")) {
            campoNumero2.setText("0");
        }
    }//GEN-LAST:event_boton0MouseClicked

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton0ActionPerformed

    private void campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoActionPerformed

    private void multiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicarMouseClicked
        if (campo.getText().equals("")) {
            campo.setText("*");
        }
    }//GEN-LAST:event_multiplicarMouseClicked

    private void sumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumarMouseClicked
        if (campo.getText().equals("")) {
            campo.setText("+");
        }
    }//GEN-LAST:event_sumarMouseClicked

    private void restarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restarMouseClicked
        if (campo.getText().equals("")) {
            campo.setText("-");
        }
    }//GEN-LAST:event_restarMouseClicked

    private void dividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividirMouseClicked
        if (campo.getText().equals("")) {
            campo.setText("/");
        }
    }//GEN-LAST:event_dividirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraKeyType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraKeyType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraKeyType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraKeyType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraKeyType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoResultado;
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JTextField campo;
    private javax.swing.JTextField campoNumero1;
    private javax.swing.JTextField campoNumero2;
    private javax.swing.JButton dividir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton respuesta;
    private javax.swing.JButton restar;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
